import type { Metadata } from "next";
import { Montserrat, Space_Mono } from "next/font/google"; // Import the fonts
import "./globals.css";

// Load Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],  // You can add more subsets as needed
  variable: "--font-montserrat",  // Create a CSS variable to store the font
});

// Load Space Mono font with specified weights
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],  // Specify weights
  variable: "--font-space-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${spaceMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
